language: cpp

sudo: false

compiler:
  - clang

env:
  - CONFIG=Release SHARED=1 CCOMPILE=clang CXXCOMPILE=clang++
  - CONFIG=Release SHARED=0 CCOMPILE=clang CXXCOMPILE=clang++
  - CONFIG=Debug SHARED=1 CCOMPILE=clang CXXCOMPILE=clang++
  - CONFIG=Debug SHARED=0 CCOMPILE=clang CXXCOMPILE=clang++

addons:
  apt:
    sources: &sources
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - clang
      - gcc-4.8
      - g++-4.8
      - libcppunit-dev
      - libboost1.55-all-dev
#      - libcrypto++-dev
# Note: libcrypto++-dev is not yet whitelisted, nor usable in the packaged
# version in Clang without editing a file (see below)

matrix:
  include:

    # g++-5.2
    - compiler: g++
      env: CONFIG=Release SHARED=1 CCOMPILE=gcc-5 CXXCOMPILE=g++-5
      addons:
        apt:
          sources: *sources
          packages:
            - clang
            - gcc-5
            - g++-5
            - libcppunit-dev
            - libboost1.55-all-dev

    - compiler: g++
      env: CONFIG=Release SHARED=0 CCOMPILE=gcc-5 CXXCOMPILE=g++-5
      addons:
        apt:
          sources: *sources
          packages:
            - clang
            - gcc-5
            - g++-5
            - libcppunit-dev
            - libboost1.55-all-dev

    - compiler: g++
      env: CONFIG=Debug SHARED=1 CCOMPILE=gcc-5 CXXCOMPILE=g++-5
      addons:
        apt:
          sources: *sources
          packages:
            - clang
            - gcc-5
            - g++-5
            - libcppunit-dev
            - libboost1.55-all-dev

    - compiler: g++
      env: CONFIG=Debug SHARED=0 CCOMPILE=gcc-5 CXXCOMPILE=g++-5
      addons:
        apt:
          sources: *sources
          packages:
            - clang
            - gcc-5
            - g++-5
            - libcppunit-dev
            - libboost1.55-all-dev

cache:
  - apt: true
  - directories:
      - cmake-3.4.0-Linux-x86_64


before_install:
# workaround for not having CMake 3.4
  - if [ ! -d "cmake-3.4.0-Linux-x86_64/bin" ]; then
      wget --no-check-certificate http://www.cmake.org/files/v3.4/cmake-3.4.0-Linux-x86_64.tar.gz;
      tar -xzf cmake-3.4.0-Linux-x86_64.tar.gz;
    fi
# Install Crypto++, and fix the dependant-name bug
#  - sudo apt-get install -y libcrypto++-dev
#  - sudo sed -i 's/\tCheckSize/\tthis->CheckSize/g' /usr/include/cryptopp/secblock.h

before_script:
  - mkdir build
  - cd build
  - CC=$CCOMPILE CXX=$CXXCOMPILE ../cmake-3.4.0-Linux-x86_64/bin/cmake -DCMAKE_BUILD_TYPE=$CONFIG -DBUILD_SHARED_LIBS=$SHARED ..

script:
  - make -j2
  - make test

after_failure:
  - cat Testing/Temporary/LastTest.log

notifications:
  email:
    on_success: change # [always|never|change] # default: change
    on_failure: change # [always|never|change] # default: always
  slack:
    rooms:
      - kazdragon:E8B4Cs4p3TiVLqHAq8wYYTr3#ci

