language: cpp

sudo: false

compiler:
#  - gcc
  - clang

#os:
#  - linux
#  - osx

env:
  - CONFIG=Release
  - CONFIG=Debug

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - clang
      - gcc-4.8
      - g++-4.8
      - libcppunit-dev
      - libboost1.55-all-dev
#      - libcrypto++-dev
# Note: libcrypto++-dev is not yet whitelisted, nor usable in the packaged
# version in Clang without editing a file (see below)

cache:
  - apt: true
  - directories:
      - cmake-3.4.0-Linux-x86_64


before_install:
# workaround for not having CMake 3.2
  - if [ ! -d "cmake-3.4.0-Linux-x86_64/bin" ]; then
      wget http://www.cmake.org/files/v3.4/cmake-3.4.0-Linux-x86_64.tar.gz;
      tar -xzf cmake-3.4.0-Linux-x86_64.tar.gz;
    fi
# Install Crypto++, and fix the dependant-name bug
#  - sudo apt-get install -y libcrypto++-dev
#  - sudo sed -i 's/\tCheckSize/\tthis->CheckSize/g' /usr/include/cryptopp/secblock.h

before_script:
  - mkdir build
  - cd build
  - ../cmake-3.4.0-Linux-x86_64/bin/cmake -DCMAKE_BUILD_TYPE=$CONFIG ..

script:
  - make -j2
  - make test

after_failure:
  - cat Testing/Temporary/LastTest.log

notifications:
  email:
    on_success: change # [always|never|change] # default: change
    on_failure: change # [always|never|change] # default: always
  slack:
    rooms:
      - kazdragon:E8B4Cs4p3TiVLqHAq8wYYTr3#ci

