language: cpp

sudo: required

compiler:
#  - gcc
  - clang

#os:
#  - linux
#  - osx

#env:
#  - config=Release
#  - config=Debug

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - clang
      - gcc-4.8
      - g++-4.8
      - libcppunit-dev
      - libboost1.55-all-dev
#      - libcrypto++-dev
# Note: libcrypto++-dev is not yet whitelisted, nor usable in the packaged
# version in Clang without editing a file (see below)

before_install:
  - sudo apt-get install -y libcrypto++-dev
# workaround for not having CMake 3.2
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz
  - tar -xzf cmake-3.2.3-Linux-x86_64.tar.gz
  - sudo cp -fR cmake-3.2.3-Linux-x86_64/* /usr
# Fix the dependant-name bug in crypto++
  - sudo sed -i 's/\tCheckSize/\tthis->CheckSize/g' /usr/include/cryptopp/secblock.h

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make -j2 && make test || (cat Testing/Temporary/LastTest.log && false)

notifications:
  email:
#    recipients:
#      - one@example.com
#      - other@example.com
    on_success: change # [always|never|change] # default: change
    on_failure: change # [always|never|change] # default: always

