# This sub-file documents changes in the Makefile for the Linux platform
# Some Linux distributions require the pthreads library to be
# stated explicitly
LIBS      += -lpthread
TEST_LIBS += -lpthread
